hystrix:
  command:
    promoCodeByProductId:
      execution.isolation.thread.timeoutInMilliseconds: 10000
      execution.isolation.strategy: SEMAPHORE
      circuitBreaker.requestVolumeThreshold: 4
server:
  port: 5506
  contextPath: /v1/mpcs

springfox:
  documentation:  
    swagger:
      v2:
        path: /api-docs
          
microservice:
  auditing:
    services: true

resturant:
  name: test

spring:
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1 
graphite:
  enabled: true
  hostname: localhost
  port: 2003
  period: 60
  prefix: mpcs
  appprefix: aem-connector-service      
---
spring:
  profiles: local,test
  zipkin:
    base-url: http://localhost:9411/     
---
spring:
  profiles: uat
  zipkin:
    base-url: http://zipkin:9411/

  